[package]
name = "emily-rust"
version = "0.0.1"
authors = [
	"1011X <1011XXXXX@gmail.com>"
]

[dependencies]
nom = "1.2.3"
getopts = "0.2.14"
regex = "0.1.41"
lazy_static = "0.1.15"
regex-syntax = "0.2.2"
