[package]
name = "emily-rust"
version = "0.0.1"
authors = [
	"1011X <1011XXXXX@gmail.com>"
]

[dependencies]
getopts = "0.2.14"
lazy_static = "0.1.15"

[dependencies.nom]
version = "1.2.3"
features = ["regexp"]
